services:
  postgres:
    container_name: liqu1tent
    image: postgres:16.2
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: liqu1tent
    networks:
      - net

volumes:
  postgres: {}

networks:
  net:
    driver: bridge
