/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFillerOracle,
  IFillerOracleInterface,
} from "../../../contracts/interfaces/IFillerOracle";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "settlementContract",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "swapper",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "nonce",
            type: "uint256",
          },
          {
            internalType: "uint32",
            name: "originChainId",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "initiateDeadline",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "fillDeadline",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "destinationChainId",
            type: "uint32",
          },
          {
            internalType: "bytes32",
            name: "destinationReceiver",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "destinationSettlementContract",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "originToken",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "originAmount",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "destinationToken",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "destinationAmount",
            type: "uint256",
          },
        ],
        internalType: "struct OrderLib.CrossChainOrder",
        name: "order",
        type: "tuple",
      },
      {
        internalType: "bytes32",
        name: "orderHash",
        type: "bytes32",
      },
    ],
    name: "reportSettlementAttempt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFillerOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IFillerOracleInterface {
    return new Interface(_abi) as IFillerOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFillerOracle {
    return new Contract(address, _abi, runner) as unknown as IFillerOracle;
  }
}
